# Generated by Django 3.2.10 on 2023-03-27 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kart', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='productdb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Category', models.CharField(blank=True, max_length=30, null=True)),
                ('Productname', models.CharField(blank=True, max_length=30, null=True)),
                ('Quantity', models.IntegerField(blank=True, max_length=30, null=True)),
                ('Description', models.CharField(blank=True, max_length=30, null=True)),
                ('Price', models.IntegerField(blank=True, max_length=30, null=True)),
                ('Image', models.ImageField(blank=True, null=True, upload_to='Products')),
            ],
        ),
    ]
